"""
QWEN3-CODER ULTIMATE — Test Generator v1.0
Generate unit tests from function signatures, docstrings, and AST analysis.
Supports pytest (Python) and Jest (JS/TS).
"""

import ast
import re
import os
import subprocess
from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class FunctionSignature:
    name:       str
    args:       list[tuple[str, str]]  # [(arg_name, type_hint)]
    returns:    str
    docstring:  str
    file:       str
    line:       int
    is_async:   bool = False
    is_method:  bool = False
    class_name: str = ""
    source:     str = ""


@dataclass
class GeneratedTest:
    function:    str
    file:        str
    test_code:   str
    test_file:   str
    framework:   str
    cases_count: int = 0


class TestGenerator:
    """
    AI-powered test generator that:
    1. Extracts function signatures via AST
    2. Generates comprehensive tests using LLM
    3. Covers: happy path, edge cases, error cases, type checks
    4. Measures coverage gap and generates targeted tests
    """

    PYTEST_TEMPLATE = '''"""
Auto-generated tests for {module_name}
Generated by QWEN3-CODER ULTIMATE
"""
import pytest
{imports}

{tests}
'''

    JEST_TEMPLATE = '''/**
 * Auto-generated tests for {module_name}
 * Generated by QWEN3-CODER ULTIMATE
 */
{imports}

{tests}
'''

    def __init__(self, client, model: str):
        self.client = client
        self.model  = model

    def _call(self, messages: list, max_tokens: int = 3000) -> str:
        try:
            resp = self.client.chat.completions.create(
                model=self.model, messages=messages,
                max_tokens=max_tokens, temperature=0.15, stream=False,
            )
            return resp.choices[0].message.content or ""
        except Exception as e:
            return f"# LLM error: {e}"

    # ── EXTRACT SIGNATURES ────────────────────────────────────────────────────
    def extract_signatures(self, filepath: str) -> list[FunctionSignature]:
        """Extract all function signatures from a Python file via AST."""
        fp = Path(filepath)
        if not fp.exists() or fp.suffix != ".py":
            return []

        content = fp.read_text(encoding="utf-8", errors="replace")
        try:
            tree = ast.parse(content, filename=filepath)
        except SyntaxError:
            return []

        sigs     = []
        lines    = content.splitlines()

        class SigVisitor(ast.NodeVisitor):
            current_class = None

            def visit_ClassDef(self, node):
                old = self.current_class
                self.current_class = node.name
                self.generic_visit(node)
                self.current_class = old

            def visit_FunctionDef(self, node):
                self._process(node)

            def visit_AsyncFunctionDef(self, node):
                self._process(node)

            def _process(self, node):
                args = []
                all_args = node.args.args + node.args.posonlyargs
                annotations = {a.arg: a.annotation for a in all_args if a.annotation}
                for arg in all_args:
                    if arg.arg == "self":
                        continue
                    type_hint = ""
                    if arg.arg in annotations:
                        try:
                            type_hint = ast.unparse(annotations[arg.arg])
                        except Exception:
                            type_hint = "Any"
                    args.append((arg.arg, type_hint))

                returns = ""
                if node.returns:
                    try:
                        returns = ast.unparse(node.returns)
                    except Exception:
                        returns = "Any"

                docstring = ""
                if (node.body and isinstance(node.body[0], ast.Expr) and
                        isinstance(node.body[0].value, ast.Constant)):
                    docstring = str(node.body[0].value.value)

                end_line = node.end_lineno or node.lineno
                source   = "\n".join(lines[node.lineno - 1:end_line])

                sigs.append(FunctionSignature(
                    name       = node.name,
                    args       = args,
                    returns    = returns,
                    docstring  = docstring,
                    file       = filepath,
                    line       = node.lineno,
                    is_async   = isinstance(node, ast.AsyncFunctionDef),
                    is_method  = self.current_class is not None,
                    class_name = self.current_class or "",
                    source     = source[:500],
                ))

        visitor = SigVisitor()
        visitor.visit(tree)
        return sigs

    # ── GENERATE TESTS FOR ONE FUNCTION ──────────────────────────────────────
    def generate_for_function(self, sig: FunctionSignature,
                               framework: str = "pytest") -> str:
        """Generate test code for a single function using LLM."""
        system = f"""You are an expert at writing {framework} tests.
Generate comprehensive tests covering:
1. Happy path (normal inputs → expected output)
2. Edge cases (empty, zero, None, boundary values)
3. Error cases (invalid inputs → exceptions)
4. Type validation (wrong types)
5. If async: use pytest-asyncio or async jest

Rules:
- Write ONLY the test functions/cases, no imports, no setup code
- Use descriptive test names: test_<function>_<scenario>
- Each test must have a clear assertion
- For methods, include class instantiation
- For functions with side effects (file I/O, DB), use mocks
- Keep tests isolated and deterministic
- Output only valid Python (no markdown)"""

        args_desc = ", ".join(
            f"{name}: {hint}" if hint else name
            for name, hint in sig.args
        )
        context = (
            f"Function: {sig.name}({args_desc}) -> {sig.returns or 'None'}\n"
            f"{'Class: ' + sig.class_name + chr(10) if sig.class_name else ''}"
            f"{'Async: yes' + chr(10) if sig.is_async else ''}"
            f"{'Docstring: ' + sig.docstring[:300] + chr(10) if sig.docstring else ''}"
            f"Source:\n{sig.source}"
        )

        raw = self._call(
            [{"role": "system", "content": system},
             {"role": "user",   "content": f"Generate tests for:\n{context}"}],
            max_tokens=2000,
        )

        clean = self._clean_code(raw)
        return clean

    # ── GENERATE TEST FILE ────────────────────────────────────────────────────
    def generate_test_file(self, filepath: str, framework: str = "pytest",
                            output_dir: str = "tests") -> GeneratedTest:
        """Generate a complete test file for all functions in a Python file."""
        fp   = Path(filepath)
        sigs = self.extract_signatures(filepath)

        if not sigs:
            return GeneratedTest(
                function="all", file=filepath,
                test_code="# No testable functions found.",
                test_file="", framework=framework,
            )

        public_sigs = [s for s in sigs if not s.name.startswith("__")]
        if not public_sigs:
            public_sigs = sigs

        module_name  = fp.stem
        module_import = fp.stem

        test_blocks  = []
        for sig in public_sigs[:15]:
            block = f"# Tests for {sig.name}()\n"
            block += self.generate_for_function(sig, framework)
            test_blocks.append(block)

        test_body    = "\n\n".join(test_blocks)
        imports_line = f"from {module_import} import {', '.join(s.name for s in public_sigs[:15])}"

        if framework == "pytest":
            if any(s.is_async for s in public_sigs):
                imports_line += "\nimport pytest_asyncio\nimport asyncio"
            full_code = self.PYTEST_TEMPLATE.format(
                module_name = module_name,
                imports     = imports_line,
                tests       = test_body,
            )
        else:
            full_code = self.JEST_TEMPLATE.format(
                module_name = module_name,
                imports     = f"const {{ {', '.join(s.name for s in public_sigs[:15])} }} = require('./{module_name}');",
                tests       = test_body,
            )

        out_dir   = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        ext       = ".test.js" if framework == "jest" else "_test.py"
        test_file = str(out_dir / f"test_{module_name}{ext}")

        Path(test_file).write_text(full_code, encoding="utf-8")

        total_cases = len(re.findall(r"def test_", full_code)) + len(re.findall(r"it\s*\(", full_code))

        return GeneratedTest(
            function    = "all",
            file        = filepath,
            test_code   = full_code,
            test_file   = test_file,
            framework   = framework,
            cases_count = total_cases,
        )

    # ── COVERAGE GAP ANALYSIS ─────────────────────────────────────────────────
    def analyze_coverage_gaps(self, filepath: str, test_dir: str = "tests") -> dict:
        """Identify functions missing tests in the test directory."""
        sigs = self.extract_signatures(filepath)
        if not sigs:
            return {"missing": [], "covered": [], "coverage_pct": 100}

        func_names  = {s.name for s in sigs if not s.name.startswith("_")}
        covered     = set()

        for test_fp in Path(test_dir).rglob("*.py"):
            try:
                content = test_fp.read_text(encoding="utf-8", errors="replace")
                for name in func_names:
                    if name in content:
                        covered.add(name)
            except Exception:
                pass

        missing = func_names - covered
        pct     = round(len(covered) / len(func_names) * 100, 1) if func_names else 100

        return {
            "missing":      sorted(missing),
            "covered":      sorted(covered),
            "coverage_pct": pct,
            "total_funcs":  len(func_names),
        }

    def fill_coverage_gaps(self, filepath: str, test_dir: str = "tests",
                           framework: str = "pytest") -> str:
        """Generate tests specifically for uncovered functions."""
        gaps = self.analyze_coverage_gaps(filepath, test_dir)
        if not gaps["missing"]:
            return f"✅ All public functions in {filepath} have tests ({gaps['coverage_pct']}% coverage)."

        all_sigs  = self.extract_signatures(filepath)
        gap_sigs  = [s for s in all_sigs if s.name in set(gaps["missing"])]
        module    = Path(filepath).stem
        out_file  = Path(test_dir) / f"test_{module}_gaps.py"

        blocks    = []
        for sig in gap_sigs:
            block = f"# Tests for {sig.name}() — previously uncovered\n"
            block += self.generate_for_function(sig, framework)
            blocks.append(block)

        out_file.parent.mkdir(parents=True, exist_ok=True)
        imports = f"from {module} import {', '.join(s.name for s in gap_sigs)}"
        content = f'"""Gap coverage tests for {module}"""\nimport pytest\n{imports}\n\n' + "\n\n".join(blocks)
        out_file.write_text(content, encoding="utf-8")

        return (
            f"✅ Generated {len(gap_sigs)} missing test suite(s)\n"
            f"   Coverage: {gaps['coverage_pct']}% → ~{min(100, gaps['coverage_pct'] + len(gap_sigs)*5):.0f}%\n"
            f"   File: {out_file}\n"
            f"   Missing tests for: {', '.join(s.name for s in gap_sigs)}"
        )

    # ── MUTATION TESTING HINT ─────────────────────────────────────────────────
    def suggest_mutations(self, filepath: str) -> str:
        """Ask the LLM to suggest what mutations would break tests (property-based hints)."""
        fp = Path(filepath)
        if not fp.exists():
            return f"File not found: {filepath}"

        content = fp.read_text(encoding="utf-8", errors="replace")[:3000]
        raw = self._call([
            {"role": "system", "content": (
                "You are a mutation testing expert. Analyze the code and suggest:\n"
                "1. Which operations if mutated (>, >=, +, -, ==, !=) would break correct tests\n"
                "2. Property-based test ideas using Hypothesis\n"
                "3. The most critical paths to test\n"
                "Be concise and specific."
            )},
            {"role": "user", "content": f"File: {filepath}\n\n{content}"},
        ], max_tokens=800)
        return raw

    # ── RUN TESTS ─────────────────────────────────────────────────────────────
    def run_tests(self, test_file_or_dir: str = "tests",
                  framework: str = "pytest") -> dict:
        """Run the test suite and return results."""
        if framework == "pytest":
            cmd = f"python -m pytest {test_file_or_dir} -v --tb=short"
        elif framework == "jest":
            cmd = f"npx jest {test_file_or_dir} --no-coverage"
        else:
            return {"error": f"Unknown framework: {framework}"}

        try:
            result = subprocess.run(
                cmd, shell=True, capture_output=True, text=True, timeout=120
            )
            output = result.stdout + result.stderr
            passed = result.returncode == 0

            total   = len(re.findall(r"PASSED|passed", output))
            failed  = len(re.findall(r"FAILED|failed", output))
            errors  = len(re.findall(r"ERROR|error", output))

            return {
                "passed":      passed,
                "total":       total,
                "failed":      failed,
                "errors":      errors,
                "output":      output[-3000:],
                "returncode":  result.returncode,
            }
        except subprocess.TimeoutExpired:
            return {"error": "Tests timed out (120s)"}
        except Exception as e:
            return {"error": str(e)}

    # ── HELPERS ───────────────────────────────────────────────────────────────
    def _clean_code(self, raw: str) -> str:
        raw = re.sub(r"```python\n?", "", raw)
        raw = re.sub(r"```\n?",       "", raw)
        raw = raw.strip()
        return raw

    def format_result(self, gen: GeneratedTest) -> str:
        return (
            f"✅ Tests generated for {gen.file}\n"
            f"   Framework: {gen.framework}\n"
            f"   Test file: {gen.test_file}\n"
            f"   Test cases: {gen.cases_count}\n\n"
            f"Preview:\n{gen.test_code[:800]}"
        )
